name: Deploy Age Calculator to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (if any)
        run: |
          npm install -g serve
          
      - name: Validate HTML
        uses: actions/github-script@v6
        with:
          script: |
            const { readFileSync } = require('fs')
            const html = readFileSync('./index.html', 'utf8')
            if (!html.includes('<html') || !html.includes('Age Calculator')) {
              core.setFailed('Invalid HTML file structure')
            }

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true
          force_orphan: true